site_name: DataTableBundle
site_description: Streamlines creation process of the data tables in Symfony applications.

repo_url: https://github.com/kreyu/data-table-bundle
repo_name: kreyu/data-table-bundle

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - 'Introduction':
    - 'index.md'
    - 'Getting started':
      - 'Installation': 'getting-started/installation.md'
      - 'Usage': 'getting-started/usage.md'
    - 'Philosophy':
      - 'Understanding the Types API': 'philosophy/understanding-types-api.md'
  - 'Reference':
    - 'Columns':
      - 'reference/columns/index.md'
      - 'Built in column types':
        - Common types:
          - Text: 'reference/columns/types/text.md'
          - Number: 'reference/columns/types/number.md'
          - Boolean: 'reference/columns/types/boolean.md'
          - DateTime: 'reference/columns/types/datetime.md'
          - Link: 'reference/columns/types/link.md'
        - Special types:
          - Collection: 'reference/columns/types/collection.md'
          - Form: 'reference/columns/types/form.md'
          - Template: 'reference/columns/types/template.md'
          - Actions: 'reference/columns/types/actions.md'
        - Base types:
          - Column: 'reference/columns/types/column.md'
      - 'Creating custom column type': 'reference/columns/creating_custom_column_type.md'
      - 'Creating column type extension': 'reference/columns/creating_column_type_extension.md'
    - 'Filters':
      - 'reference/filters/index.md'
      - 'Built in filter types':
        - Doctrine ORM types:
          - String: 'reference/filters/types/doctrine-orm/string.md'
          - Numeric: 'reference/filters/types/doctrine-orm/numeric.md'
          - Boolean: 'reference/filters/types/doctrine-orm/boolean.md'
          - Date: 'reference/filters/types/doctrine-orm/date.md'
          - DateTime: 'reference/filters/types/doctrine-orm/datetime.md'
          - Entity: 'reference/filters/types/doctrine-orm/entity.md'
          - Callback: 'reference/filters/types/doctrine-orm/callback.md'
        - Base types:
          - Filter: 'reference/filters/types/filter.md'
      - 'Creating custom filter type': 'reference/filters/creating_custom_filter_type.md'
      - 'Creating filter type extension': 'reference/filters/creating_filter_type_extension.md'
    - 'Actions':
        - 'reference/actions/index.md'
        - 'Built in action types':
          - Common types:
            - Link: 'reference/actions/types/link.md'
            - Button: 'reference/actions/types/button.md'
            - Form: 'reference/actions/types/form.md'
          - Base types:
            - Action: 'reference/actions/types/action.md'
        - 'Creating custom action type': 'reference/actions/creating_custom_action_type.md'
        - 'Creating action type extension': 'reference/actions/creating_action_type_extension.md'
    - Exporters:
      - 'reference/exporters/index.md'
      - 'Built in exporter types':
        - 'PhpSpreadsheet':
          - Csv: 'reference/exporters/types/phpspreadsheet/csv.md'
          - Html: 'reference/exporters/types/phpspreadsheet/html.md'
          - Ods: 'reference/exporters/types/phpspreadsheet/ods.md'
          - Pdf: 'reference/exporters/types/phpspreadsheet/pdf.md'
          - Xls: 'reference/exporters/types/phpspreadsheet/xls.md'
          - Xlsx: 'reference/exporters/types/phpspreadsheet/xlsx.md'
          - PhpSpreadsheet: 'reference/exporters/types/phpspreadsheet/phpspreadsheet.md'
        - 'Base types':
          - Exporter: 'reference/exporters/types/exporter.md'
      - 'Creating custom exporter type': 'reference/exporters/creating_custom_exporter_type.md'
      - 'Creating exporter type extension': 'reference/exporters/creating_exporter_type_extension.md'
    - 'Sorting': 'reference/sorting.md'
    - 'Pagination': 'reference/pagination.md'
    - 'Personalization': 'reference/personalization.md'
    - 'Persistence': 'reference/persistence.md'
    - 'Theming': 'reference/theming.md'
    - 'Proxy queries': 'reference/proxy-queries.md'
    - 'Configuration': 'reference/configuration.md'
    - 'Twig': 'reference/twig.md'
  - 'Advanced':
    - 'Integration with Symfony UX Turbo': 'advanced/integration-with-symfony-ux-turbo.md'
    - 'Integration with Symfony Forms': 'advanced/integration-with-symfony-forms.md'
    - 'Creating custom request handler': 'advanced/creating-custom-request-handler.md'
    - 'Creating data table type extension': 'advanced/creating-data-table-type-extension.md'

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - include-markdown
  - macros